### ISSUE TITLE
Include Gatsby in documentation

### ISSUE THREAD

**Issue by its-a-lisa-at-work** [cloud-gov/federalist.18f.gov#439]
[Customizing your site](https://federalist.18f.gov/documentation/customization/) page only references Jekyll and doesn't mention Gatsby as a static site generator. 

[Managing site settings](https://federalist.18f.gov/documentation/#managing-site-settings) doesn't mention Gatsby

**Comment by amirbey** [comment]
thanks for raising this @its-a-lisa-at-work ... we will address this ASAP

**Comment by davemcorwin** [comment]
@its-a-lisa-at-work I agree that it's confusing that we only have this type of documentation for Jekyll and not other sites and we do list Gatsby and others in [supported site engines](https://federalist.18f.gov/documentation/supported-site-engines/).

I think we will be moving toward providing less of this type of documentation and referring more to Jekyll's own documentation going forward as this is a bit of maintenance burden.

This issue is included in an existing Epic for a larger overhaul of the documentation

**Comment by its-a-lisa-at-work** [comment]
awesome, ,thanks!

I would have figured that Gatsby is supported like Jekyll since there is a [template](https://federalist.18f.gov/documentation/templates/) for Jekyll and Gatsby

**Comment by apburnes** [comment]
No
